# ─── STAGE 0: Build ROS2 + common_packages ───────────────────────────────
FROM ubuntu:{{ ubuntu }} AS common-builder

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    locales \
    curl \
    gnupg2 \
    lsb-release \
    software-properties-common \
    git && \
    locale-gen en_US.UTF-8 


ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

# Add ROS2 apt repository
RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add - && \
    sh -c 'echo "deb [arch=$(dpkg --print-architecture)] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2-latest.list'

# Install ROS2 base + build tools
RUN apt-get update && apt-get install -y \
    ros-{{ ros_distro }}-ros-base \
    python3-colcon-common-extensions \
    python3-rosdep \
    python3-pip && \
    pip3 install -U vcstool \
    rosdep init

# Overlay your shared packages
{% for pkg in common_pkgs %}
COPY {{ pkg.folder }}/ros_ws/src/{{ pkg.name }} /ros_ws_common/src/{{ pkg.name }}
{% endfor %}

WORKDIR /ros_ws_common
RUN colcon build --symlink-install --install-base install


# automatically source ROS2 and common overlay
RUN echo "source /opt/ros/{{ ros_distro }}/setup.bash" >> ~/.bashrc && \
    echo "source /ros_ws_common/install/setup.bash" >> ~/.bashrc

ENTRYPOINT ["/bin/bash","-lc","exec \"$@\"","--"]
CMD ["bash"]
